dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=mobilesite'

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=mobilesite_test'

prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=symfonyhackathon20110924-SG3LGFG4.dotcloud.com;dbname=mobilesite;port=15166'
      username: root
      password: 1xt6L231SqDtl3p1bspY

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      username: mobilesite
      password: mobilesite
      attributes:
        default_table_charset: utf8
        default_table_collate: utf8_bin
